version: '3.7'

services:
  regression:
    image: python:3.12.4-slim-bullseye
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: /bin/sh -c "pytest -sv --alluredir=./allure-results"
    working_dir: /app